services:
  3dscene-frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - ./frontend:/app

  3dscene-api:
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend/:/code

  3dscene-worker-heavy:
    volumes:
      - ./backend/:/code
  
  3dscene-worker-email:
    volumes:
      - ./backend/:/code

  3dscene-reverse-proxy:
    # volumes:
    #   - ./reverse-proxy/certs/:/etc/nginx/certs/
    build:
      context: ./reverse-proxy
      dockerfile: Dockerfile

